# Generated by Django 6.0.4 on 2026-04-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_guide_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection — visible to the student.'),
        ),
    ]
